apiVersion: v1
kind: Service
metadata:
  name: weather-web-app-service
spec:
  selector:
    app: weather-web-app  # Matches the label in the deployment
  ports:
    - protocol: TCP
      port: 8080  # Port that the service will expose
      targetPort: 8080  # Port inside the container
  type: LoadBalancer  # Expose the app using LoadBalancer for external access
